### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by janaxhell** [rombat/musicbee-navidrome-sync#11]
Hi,
I'm trying to export my MB library to CSV, but around 35% it always crashes with this error

MusicBee v3.6.8909.34028D  (Win10.0), 2 lug 2024 15:56:

```
System.OutOfMemoryException: Generata eccezione di tipo 'System.OutOfMemoryException'.
   in System.String.Join(String separator, String[] value, Int32 startIndex, Int32 count)
   in System.String.Join(String separator, String[] value)
   in MusicBeePlugin.LibraryReportsCommand.AggregatedTags.add(String url, String[] groupingValues, String[] functionValues, List`1 functionTypes, String[] parameter2Values, Boolean totals)
   in MusicBeePlugin.LibraryReportsCommand.previewTrackList()
   in MusicBeePlugin.PluginWindowTemplate.serializedOperation()
   in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()
```
My OS is Win10, the library is on an OpenMediaVault samba share which I use both from Navidrome and MusicBee.
My PC has 32Gb of RAM and when this happens it's not even near to half of that. The MB process itself is around 1,2 Gb while working. Tried with a freshly booted PC without any other job running.
MusicBee stats count 34.830 albums. 
Any advice for this?

EDIT Well, it seems either a MB or a plugin bug, I asked about it [here](https://getmusicbee.com/forum/index.php?topic=3833.msg225066#msg225066), we'll see if someone finds a solution. 

BTW, what version of MB and plugin are you using? How many albums have you scanned?

**Comment by rombat** [comment]
Hi,
Yep it seems to be an issue related to MusicBee / its plugin
I'm using MusicBee 3.5.8698 with Additional Tagging & Reporting Tools 8.0.8764 (you can check the [README](https://github.com/rombat/musicbee-navidrome-sync/blob/master/README.md) for the tested versions)
I scan about 6500 albums / 98k tracks.

**Comment by rombat** [comment]
I'm closing the issue since it's not related to MBNDS, but don't hesitate if you have any question

**Comment by janaxhell** [comment]
Ok, may I ask you how did you configure AT&RT plugin to export Library Reports?
Yesterday I have updated it to v8.1.8922, but the left column from where I selected tags to be exported before disappeared and I can't find any info about even in the relative github wiki.
My Library Reports now looks like this, how can I add tags to be exported? Does your v8.0.8764 look like this?

![image](https://github.com/rombat/musicbee-navidrome-sync/assets/55061479/a518d3b7-155e-43ad-80e2-84ba64357150)

**Comment by rombat** [comment]
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/9024503/f1ee37ed-f7a2-473e-b51f-e8e0378b399d)
it's in column definitions, here's what mine looks like

**Comment by janaxhell** [comment]
I cannot select Function = Grouping because it's greyed out, nor assign a name to the preset. If I click New Preset, it's "Empty Preset", if I write a name THEN click New Preset, it happens the same.

![image](https://github.com/rombat/musicbee-navidrome-sync/assets/55061479/bc6ef014-0208-492d-be19-83669b761ae1)

**Comment by rombat** [comment]
First, create a new Preset by clicking New Preset
Give it a name just by typeing anything in the field where "(Auto preset name)" is displayed on your screenshot
Then, you need to click on Add, then Function/Tag select is available
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/9024503/117c8e2f-b8a9-4d41-9242-3ad68c2b6ebc)
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/9024503/c2f0547d-f876-4654-9b31-05dcbe46feec)

**Comment by janaxhell** [comment]
Ahh, it's a graphic issue, in my case "Add" and Save buttons are empty, but if I click them, they do what you say. 
I will now create the preset and launch a scan, then feedback, will take hours.

![image](https://github.com/rombat/musicbee-navidrome-sync/assets/55061479/1b8e55c3-13fe-41f1-8f34-0480149e978e)

**Comment by janaxhell** [comment]
Sigh, nope, it's bugged... 

![image](https://github.com/rombat/musicbee-navidrome-sync/assets/55061479/53db7cff-2bc6-4453-8c24-5322df504153)

After a couple of minutes it crashed at 6%..

**Comment by rombat** [comment]
Well, I can't do anything about that unfortunately. You'll have to wait for an answer of the plugin code maintainer(s)

**Comment by janaxhell** [comment]
Hi again, I've tried to rollback to MusicBee 3.5.8591 and with latest plugin version it crashed as well. It did not have the graphic glitches, but still didn't work. Since the plugin page always links to the latest version, could you send me the version that works for you?

**Comment by janaxhell** [comment]
Managed to make this work (it was a 1.3 Gb memory limit of MB that I managed to raise to 4 Gb), but now it's your app that give error, I will now open a different issue. 
I did what explained here https://getmusicbee.com/forum/index.php?topic=22778.0
With 34950 albums, I barely managed (took a couple of times to NOT crash again) to produce MusicBee_Export.csv
I have used MB 3.5.8698 and mb_TagTools 8.0.8794

**Comment by rombat** [comment]
> Managed to make this work (it was a 1.3 Gb memory limit of MB that I managed to raise to 4 Gb), but now it's your app that give error, I will now open a different issue. I did what explained here https://getmusicbee.com/forum/index.php?topic=22778.0 With 34950 albums, I barely managed (took a couple of times to NOT crash again) to produce MusicBee_Export.csv I have used MB 3.5.8698 and mb_TagTools 8.0.8794

I wasn't aware of this limit, but it's good to know that, thanks for the link !
I've answered to your new issue,  I may have a few ideas on how to fix it, but I need some more information to be sure, so let's continue [there](https://github.com/rombat/musicbee-navidrome-sync/issues/13) from now on 👍🏼
