### ISSUE TITLE
App starts syncing, but at some point stops with error

### ISSUE THREAD

**Issue by janaxhell** [rombat/musicbee-navidrome-sync#13]
Done everything explained in home, this is what happens during fullSync -f:

```
W:\- 111111>musicbee-navidrome-sync.exe fullSync -f
Command running with following options: { db: 'navidrome.db', datetimeFormat: 'DD/MM/YYYY HH:mm', first: true }
DB has been backed up to ./backups/navidrome_2024-07-17_14-50-21_backup.db
Connection has been established successfully.
MusicBee_Export.csv parsed successfully, 11376 potential tracks to be updated
Processing tracks...
 ██████████████████████░░░░░░░░░░░░░░░░░░ 53% | ETA: 23s | 6135/11376An error as occured, restoring DB file...
 ████████████████████████████████████████ 100% | ETA: 0s | 11376/11376node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Database.<anonymous> (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:179:27)
    at Database.serialize (<anonymous>)
    at C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:177:50
    at new Promise (<anonymous>)
    at Query.run (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:177:12)
    at C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\sequelize.js:311:28
    at async SQLiteQueryInterface.insert (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\model.js:2432:35)
    at async C:\snapshot\musicbee-navidrome-sync\lib\handlers\MBNDSynchronizer.js {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'user_id must be unique',
      type: 'unique violation',
      path: 'user_id',
      value: '47607edb-1086-43fc-985e-754542a6714a',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: '495ff38e-cbdc-41ef-ae0e-03a409c9050d',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'item_id must be unique',
      type: 'unique violation',
      path: 'item_id',
      value: '0cdd091a7f36866c976842c86cf82d45',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: '495ff38e-cbdc-41ef-ae0e-03a409c9050d',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'item_type must be unique',
      type: 'unique violation',
      path: 'item_type',
      value: 'media_file',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: '495ff38e-cbdc-41ef-ae0e-03a409c9050d',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: annotation.user_id, annotation.item_id, annotation.item_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
  },
  original: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: annotation.user_id, annotation.item_id, annotation.item_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
  },
  fields: [ 'user_id', 'item_id', 'item_type' ],
  sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
}
```

**Comment by rombat** [comment]
it's kind of weird. The issue here is an unique constraint violation. 
there is a unique constraint in Annotation (where your playcount is stored) for `user_id` (your user id), `item_id` (the found track id), and `item_type` (which has a value of `media_file` for tracks).
This annotation is supposed to be created once per track. Your issue suggests that it's already been created. But it's created only when no annotation is found for a given track.

I may have some ideas on how to fix this, but I need some more information to diagnose the issue properly.
Can you share me both your initial `navidrome.db` file and your `MusicBee_Export.csv` please ?
Thanks in advance.

**Comment by janaxhell** [comment]
Ok, here it is. Link will expire in 3 days, but I prefer you to confirm you got it, so I will remove the link from here.
[redacted]

**Comment by rombat** [comment]
> Ok, here it is. Link will expire in 3 days, but I prefer you to confirm you got it, so I will remove the link from here

Thanks, got it (huge db indeed, mine is about 250Mo).
I have quite a busy schedule these days, at least up to next Sunday, maybe even later. I'm not sure if I'll be able to take a look at it quickly, but don't worry, I will eventually fix this.
I'll keep you informed.

**Comment by janaxhell** [comment]
I don't know if it matters, but my Navidrome library is split between /music and /unmapped, because I use Lidarr, so everything unknown to Musicbrainz is moved to a mirrored hierarchy in /unmapped. This way Navidrome sees everything in a transparent way and Lidarr doesn't bitch about unmapped albums. Same for MusicBee, the library is /music+/unmapped via samba share.

**Comment by rombat** [comment]
> I don't know if it matters, but my Navidrome library is split between /music and /unmapped, because I use Lidarr, so everything unknown to Musicbrainz is moved to a mirrored hierarchy in /unmapped. This way Navidrome sees everything in a transparent way and Lidarr doesn't bitch about unmapped albums. Same for MusicBee, the library is /music+/unmapped via samba share.

I don't know if it's related for now, I'll see that when I'll look into your files, but thanks for the information

**Comment by rombat** [comment]
@janaxhell I get the following error scanning your file:
`Error: SQLITE_CORRUPT: database disk image is malformed`
So I can't use it to debug your issue for the moment

It's probably due to the fact that you copied your DB file while the DB was still active/used by navidrome
You have to either **shutdown navidrome properly** before backing it up (make sure there's no `navidrome.db-shm` or `navidrome.db-wal` lying around), or back it up with sqlite cli, for instance `sqlite3 <path to original file> ".timeout 30000" ".backup <path to backup file>`

**Comment by janaxhell** [comment]
No, Navidrome was properly shutdown, anyway I will try the sqlite mode.

**Comment by janaxhell** [comment]
I'm not familiar with sqlite3, when from navidrome folder I launch a command like 
`sqlite3 navidrome.db ".timeout 30000" ".backup navibackup.db`
CLI shows a 
 >_

waiting for some command.

**Comment by rombat** [comment]
it's a linux command so i guess it depends on the OS your navidrome is installed on
check if there's a `navibackup.db` created in navidrome folder

**Comment by janaxhell** [comment]
I'm on open media vault, which is linux. ND is in a docker container. 
path is
/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Navidrome/navidrome.db

**Comment by rombat** [comment]
is sqlite3 installed ?
can  you please shut down your docker container and reupload your db file?

**Comment by janaxhell** [comment]
Yes, I have installed sqlite3 for the purpose and navidrome is already shutdown, can you give me the full command?

**Comment by rombat** [comment]
it is the full command. you can try with a lower timeout (it's in ms)

**Comment by janaxhell** [comment]
I don't know what to do here:
![image](https://github.com/user-attachments/assets/e661cf8b-754a-4b88-89af-a74925858a20)

**Comment by rombat** [comment]
Check if the file navibackup.db has been created in this folder

**Comment by janaxhell** [comment]
No, it's not. 
```
root@openmediavault:/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Navidrome# ls -l
total 1928748
drwxrwsrwx+ 4 admin users      4096 Mar 26  2022 cache
-rw-r--r--  1 admin users 982667264 Jul 20 03:40 navidrome.db
-rw-r--r--  1 admin users     32768 Jul 20 16:55 navidrome.db-shm
-rw-r--r--  1 admin users   4911072 Jul 20 16:55 navidrome.db-wal
```

**Comment by janaxhell** [comment]
I have manually copied the navidrome.db the same way I did last time (Total Commander via samba share) and again your app crashed:

```
W:\- 111111>musicbee-navidrome-sync.exe fullSync -f
Command running with following options: { db: 'navidrome.db', datetimeFormat: 'DD/MM/YYYY HH:mm', first: true }
DB has been backed up to ./backups/navidrome_2024-07-20_18-32-40_backup.db
Connection has been established successfully.
MusicBee_Export.csv parsed successfully, 11376 potential tracks to be updated
Processing tracks...
 ██████████████████████░░░░░░░░░░░░░░░░░░ 54% | ETA: 44s | 6161/11376An error as occured, restoring DB file...
 ████████████████████████████████████████ 100% | ETA: 0s | 11376/11376node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Database.<anonymous> (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:179:27)
    at Database.serialize (<anonymous>)
    at C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:177:50
    at new Promise (<anonymous>)
    at Query.run (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\sqlite\query.js:177:12)
    at C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\sequelize.js:311:28
    at async SQLiteQueryInterface.insert (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\snapshot\musicbee-navidrome-sync\node_modules\sequelize\lib\model.js:2432:35)
    at async C:\snapshot\musicbee-navidrome-sync\lib\handlers\MBNDSynchronizer.js {
  name: 'SequelizeUniqueConstraintError',
  errors: [
    ValidationErrorItem {
      message: 'user_id must be unique',
      type: 'unique violation',
      path: 'user_id',
      value: '47607edb-1086-43fc-985e-754542a6714a',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: 'b4dc6435-c3af-48e7-b246-da275f4adb6b',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'item_id must be unique',
      type: 'unique violation',
      path: 'item_id',
      value: '0cdd091a7f36866c976842c86cf82d45',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: 'b4dc6435-c3af-48e7-b246-da275f4adb6b',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'item_type must be unique',
      type: 'unique violation',
      path: 'item_type',
      value: 'media_file',
      origin: 'DB',
      instance: Annotation {
        dataValues: {
          play_date: null,
          rating: 0,
          starred_at: null,
          ann_id: 'b4dc6435-c3af-48e7-b246-da275f4adb6b',
          item_type: 'media_file',
          user_id: '47607edb-1086-43fc-985e-754542a6714a',
          item_id: '0cdd091a7f36866c976842c86cf82d45',
          play_count: 0,
          starred: false
        },
        _previousDataValues: {
          ann_id: undefined,
          item_type: undefined,
          user_id: undefined,
          item_id: undefined,
          play_count: undefined,
          starred: undefined
        },
        uniqno: 1,
        _changed: Set(6) {
          'ann_id',
          'item_type',
          'user_id',
          'item_id',
          'play_count',
          'starred'
        },
        _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: annotation.user_id, annotation.item_id, annotation.item_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
  },
  original: [Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: annotation.user_id, annotation.item_id, annotation.item_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
  },
  fields: [ 'user_id', 'item_id', 'item_type' ],
  sql: 'INSERT INTO `annotation` (`ann_id`,`user_id`,`item_id`,`item_type`,`play_count`,`play_date`,`rating`,`starred`,`starred_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9);'
}
```

**Comment by janaxhell** [comment]
Something I noticed is that `navidrome.db` before launching your app has the size of
`982.667.264`
but after crash it's
`984.453.120`

**Comment by rombat** [comment]
The one after crash is most certainly messed up, that's why a backup is automatically created

**Comment by rombat** [comment]
> I have manually copied the navidrome.db the same way I did last time (Total Commander via samba share) and again your app crashed:
> 

I haven't fixed anything yet, so that's expected. It's the same error

**Comment by janaxhell** [comment]
So what do I do? Shall I send you the clean navidrome.db before feeding it to your app?
The one I've sent you is from after the job.
EDIT
Well, here it is if you want to compare:
[redacted]

**Comment by rombat** [comment]
> So what do I do? Shall I send you the clean navidrome.db before feeding it to your app? The one I've sent you is from after the job.

Yes please 🙏🏼 
I don't know when I'll have the time to have another look though, but I will

**Comment by rombat** [comment]
Ok, I've found out the reason of this issue.
Basically, to find a match for a given file between MusicBee export and navidrome DB, I search for a file with the same path end with 2 levels of folders (if possible).

Your MB collection have some files that share a same path end with that many levels of folders, for instance:
```
V:\data\media\music\Electro Retrowave\Carpenter Brut\Carpenter Brut - 2018 - Leather Teeth\01 - Leather Teeth.mp3
V:\data\media\music\Soundtracks Author\Carpenter Brut\Carpenter Brut - 2018 - Leather Teeth\01 - Leather Teeth.mp3
```

the file path end I check a match on here is `Carpenter Brut\Carpenter Brut - 2018 - Leather Teeth\01 - Leather Teeth.mp3` (with / in navidrome db)
which is the same for both of those files. So in navidrome, I pick the first that is found

The thing is, in navidrome, there is a unique constraint in Annotation (where your playcount, rating, last played date... are stored) for user_id (your user id), item_id (the found track id), and item_type (which has a value of media_file for tracks).
This annotation is supposed to be created once per track. 
Since for the script both of those tracks are the same, it tries to **create** a new annotation even if it already exists.

I have a solution in mind, which would imply to extend and compare the levels of folders in path of all potential tracks. But I don't have time to do that today unfortunately, I'll try to find some time to fix it during this week or maybe next weekend (busy weeks). Thanks for your patience.

I will also do some tweaks to make the script faster (which could be useful for a huge DB like yours)

**Comment by janaxhell** [comment]
Hi, thank you very much, I'm not in a hurry at all! At least my particular case forces you to broaden the usage and compatibility of your app :)
I know I have some duplicate albums for many reasons, but until now they were just duplicate entries, or entries in libraries enabled in one profile and not in another, with overlapping album choices. Also when I had to split into /music and /unmapped, I'm pretty sure Lidarr downloaded redundant albums to /music, while the same copy in /unmapped was perfectly legit. It's a very frustrating tool, but also the only one that automates downloads.

**Comment by janaxhell** [comment]
Just an update: boroda, the ATT plugin dev has made a series of modifications that allow now to produce the CSV in a minute (most likely less for whom has a smaller library) with no crash (*). While it's true that MB is more elastic with the 4Gb patch, in this case it was specifically the Preview tab of the plugin that made it blow in RAM and crash.
https://getmusicbee.com/forum/index.php?topic=3833.3495 

(*) you have to thick the Hide Preview option in the Library Report plugin tab.

**Comment by rombat** [comment]
> Just an update: boroda, the ATT plugin dev has made a series of modifications that allow now to produce the CSV in a minute (most likely less for whom has a smaller library) with no crash (*). While it's true that MB is more elastic with the 4Gb patch, in this case it was specifically the Preview tab of the plugin that made it blow in RAM and crash. https://getmusicbee.com/forum/index.php?topic=3833.3495
> 
> (*) you have to thick the Hide Preview option in the Library Report plugin tab.

Thanks, I'll have to try that !
I've just released [a new version](https://github.com/rombat/musicbee-navidrome-sync/releases) that should fix your issue. It takes about 3min to process your library.

**Comment by janaxhell** [comment]
Thanks, I am in the middle of something today, I'll check it ASAP and then feedback!
EDIT
Before going on, I have a question: since Lidarr keeps adding new albums to my Library, Navidrome is always one step ahead of MusicBee, because I have to manually import them. 
What happens if I use your app on a navidrome.db that has 100% of albums and MusicBee export that has 99%? 
Can I do that, or have I to update MusicBee library to 100% before syncing?

EDIT2
Well, I have updated MusicBee and synced with Navidrome, it worked fine!
I'm so glad to have put an order to the mess that was my Navidrome UI, I had inconsistent random likes here and there. Now I have the same of MusicBee! :)

**Comment by rombat** [comment]
> What happens if I use your app on a navidrome.db that has 100% of albums and MusicBee export that has 99%?
Can I do that, or have I to update MusicBee library to 100% before syncing?

It's the current  behavior: all track-related data are updated from MusicBee data. All albums/artists-related data are updated from resulting updates (from tracks) + existing data in Navidrome.

Glad to know that my little tool can help others like you 👍🏼
