### ISSUE TITLE
track not found

### ISSUE THREAD

**Issue by viazure** [rombat/musicbee-navidrome-sync#5]
Hello, thank you for developing this project. I encountered some problems and hope to get your help.

Currently, I am using MusicBee (3.5.8447 Store) and Navidrome (0.49.3). Following the tutorial, I have completed exporting MusicBee_Export.csv and copying navidrome.db, and I have placed them in the same directory as the musicbee-navidrome-sync.exe.

When I executed the command musicbee-navidrome-sync.exe fullSync -f, I found that the data was not updated.

```cmd
Command running with following options: { db: 'navidrome.db', first: true }
DB has been backed up to ./backups/navidrome_2023-06-10_17-39-53_backup.db
Connection has been established successfully.
MusicBee_Export.csv parsed successfully, 3895 potential tracks to be updated
Processing tracks...
 ████████████████████████████████████████ 100% | ETA: 0s | 3895/3895
0 tracks updated
Processing albums...
 ████████████████████████████████████████ 100% | ETA: 0s | 1859/1859
0 albums updated
Processing artists...
 ████████████████████████████████████████ 100% | ETA: 0s | 1189/1189
0 artists updated
fullSync completed successfully in a few seconds
```

I attempted to use the command `musicbee-navidrome-sync.exe fullSync --verbose`, but it prompted that `track not found`.

```cmd
Command running with following options: { db: 'navidrome.db', verbose: true }
DB has been backed up to ./backups/navidrome_2023-06-10_16-58-47_backup.db
Connection has been established successfully.
MusicBee_Export.csv parsed successfully, 3895 potential tracks to be updated
Processing tracks...
track not found: Adele/19/Adele - Make You Feel My Love.mp3
track not found: Adele/25/Adele  - All I Ask.flac
track not found: Adele/25/Adele  - Can't Let Go.flac
track not found: Adele/25/Adele  - I Miss You.flac
```

The attachment is a truncated version of the CSV file.
[MusicBee_Export.csv](https://github.com/rombat/musicbee-navidrome-sync/files/11712131/MusicBee_Export.csv)

**Comment by viazure** [comment]
@rombat 
Hey guy,

Greetings! I have successfully resolved the issue at hand. I discovered that the path in the media_file table of my navidrome.db was using backslashes \, which caused the program to fail in matching the corresponding tracks. By modifying the concatenation string of filePathEnd in the source code, I ultimately achieved the synchronization of data from MusicBee to Navidrome. Once again, I am grateful for the author's efforts and I hope that this issue can be addressed, allowing compatibility with such style of track paths.

Best regards, viazure.

**Comment by rombat** [comment]
Hi @viazure 
I'm really sorry about not answering your post.  I didn't see your issue, I must have missed the notification :/ I was kind of busy with work and personal stuff lately, but this project has not been abandoned, and I will improve it whenever necessary.
It's weird that your db is using backslashes, I wasn't aware of such a case. Can you provide me your db file ?
I'll fix this in another release, thanks a lot for your input !
Have a nice day :)

**Comment by viazure** [comment]
Sure, I have attached the file. @rombat 

By the way, the Navidrome service is running on my personal computer, which has Windows 11 Home edition. In the `navidrome.toml` configuration file, the `MusicFolder` setting is `MusicFolder = C:\\Users\\viazure\\OneDrive\\Music`. I'm not sure if they are the cause of the current issue.

I hope this information can help you resolve the problem.
[navidrome.zip](https://github.com/rombat/musicbee-navidrome-sync/files/11999400/navidrome.zip)

**Comment by rombat** [comment]
Oh, you're running Navidrome on Windows, so it all make sense !
I've released a new version, it should fix your issue: https://github.com/rombat/musicbee-navidrome-sync/releases/tag/v1.0.6

**Comment by viazure** [comment]
Okay, this version is working fine now. Thank you very much.

**Comment by sterling-tenn** [comment]
Hello, I've come across a very similar issue, although I've somewhat fixed it.
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/56081843/55102d6e-d396-4c52-a20e-7761a6061be5)


My setup is currently MusicBee on Windows, and transferring to Navidrome on Linux.
The `filepath` for my music files are all located as `'C:\\Users\\sterl\\OneDrive\\Music'` which seems to cause a mismatch between the `path` I'm storing my music on the Linux system in `/var/lib/navidrome/Music`

Thus the assignment to `filePathEnd` on line 208 in `MBNDSynchronizer.js` yields `OneDrive\Music\<SONG>.mp3` which does not match with search for a track in the database on line 215 of `MBNDSynchronizer.js`
```
const foundTrack = await Track.findOne({
  where: {
    [Op.and]: [
      { title: track.title },
      {
        path: {
          [Op.endsWith]: `${filePathEnd}`
        }
      }
    ]
  },
```

I've (sort of) fixed it for me personally by changing
```
const filePathEnd = `${filePathArray.length >= 2 ? filePathArray[filePathArray.length - 2] : ''}${dbFolderSeparator}${
            track.folder
          }${dbFolderSeparator}${track.filename}`;
```
to
```
const filePathEnd = `${dbFolderSeparator}${
            track.folder
          }${dbFolderSeparator}${track.filename}`;
```
so now it correctly matches and processes the tracks


For reference, my `MusicBee_Export.csv` looks like this:
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/56081843/c41528ae-392b-43df-a3af-e454b0652def)
and my `navidrome.db` `media_file` table looks like this:
![image](https://github.com/rombat/musicbee-navidrome-sync/assets/56081843/40320eba-5b0c-41f9-b0c2-b3afb01cd520)

**Comment by rombat** [comment]
@sterling-tenn I've just released [a new version](https://github.com/rombat/musicbee-navidrome-sync/releases) that should fix your issue.
