### ISSUE TITLE
Command options not working

### ISSUE THREAD

**Issue by psagat** [rombat/musicbee-navidrome-sync#7]
C:\Users\Pete\Downloads>musicbee-navidrome-sync.exe -f
error: unknown option '-f'

C:\Users\Pete\Downloads>musicbee-navidrome-sync.exe --first
error: unknown option '--first'

Documentation appears to be wrong as it states using -f or --first.

**Comment by rombat** [comment]
weird, it was previously working, I'll have a look

**Comment by rombat** [comment]
Ok I got it @psagat 
Like written in [readme](https://github.com/rombat/musicbee-navidrome-sync#%EF%B8%8F-commands), It's an option only available with `fullSync` 
It's working just fine if you run `musicbee-navidrome-sync.exe fullSync -f`
